### ISSUE TITLE
newline problem

### ISSUE THREAD

**Issue by myto2006** [nahsra/antisamy#110]
version： 1.5.13 
policy： antisamy-slashdot.xml

String dirtyInput = "{\"authorId\":\"1\",\"authorName\":\"E-W & N-S\"}";
CleanResults cr = as.scan(dirtyInput, policy);
String str = cr.getCleanHTML();
System.out.println(str);

the result: 
{&quot;authorId&quot;:&quot;1&quot;,&quot;authorName&quot;:&quot;E-W
&amp; N-S&quot;}

there is a newline after the W character. help me!

**Comment by LiuXing-R** [comment]
Hi,@myto2006 
If you just don't want to wrap, you can change the double quotation marks to single quotation marks, or no quotation marks.
```
String dirtyInput = "{'authorId':'1','authorName':'E-W & N-S'}";
```
So there will be no line breaks.

**Comment by LiuXing-R** [comment]
Or you can turn off the configuration of newline output in  antisamy-slashdot.xml
```
<directive name="formatOutput" value="true"/>
```

**Comment by spassarop** [comment]
Hello @myto2006, as @LiuXing-R pointed out, the `formatOutput` directive is why that happens. Apparently your output is just a word wrap of a certain length which does not seem to be a input we can provide. Even by changing `"` to `'` the new line will be added with enough string length.

So if you don't want your output to be formatted, change that to false.
