### ISSUE TITLE
Enhancement: Add Spotless to auto format files

### ISSUE THREAD

**Issue by davewichers** [nahsra/antisamy#112]
@spassarop - I maintain OWASP Benchmark and this year we added the Maven spotless plugin to the project and it's CI to autoformat code, and verify any pull requests have also done so before submitting any code changes. While this isn't a huge deal for AntiSamy, it's relatively easy to add.

Here's the pom entry: https://github.com/OWASP-Benchmark/BenchmarkJava/blob/master/pom.xml#L1067

Any objections to doing this? We'd have to run it once to reformat ALL the code, but then after that it will only reformat files that have changed in git.

**Comment by spassarop** [comment]
No objections. Do you want to do this after pending PRs are merged or by adding it to CI it doesn't matter?

**Comment by davewichers** [comment]
This was done as part of the 1.7.0 release.
