### ISSUE TITLE
require-closing-tags is not supported by antsamy.xsd

### ISSUE THREAD

**Issue by SushantC12** [nahsra/antisamy#147]
Please add "require-closing-tags" in antisamy.xsd file.  XSD file treats it as child element and doesn't allow custom tag.

**Comment by davewichers** [comment]
@spassarop - What do you think?

**Comment by spassarop** [comment]
Its pertinent. `require-closing-tags` is not present in any example policy file right now and that's probably why we missed it.
Nowadays it is only used when printing closing tags on SAX scanner output to end it like `<tag/>` or `<tag></tag>` if it is empty and allowed. I'll add it as optional on the default schema.

**Comment by spassarop** [comment]
A PR was made with this along with some tests. It is now included in default schema file and it should be positioned at the end if present.

**Comment by davewichers** [comment]
Fix included in v1.6.6 release.
