### ISSUE TITLE
AntiSamy should not be dependent on Xerces

### ISSUE THREAD

**Issue by wcruppel** [nahsra/antisamy#17]
Xerces does not support the attributes on a Transformer that are required in order to mitigate XXE vulnerabilities. While this may not be a huge issue for AntiSamy itself, the fact that we have to include xercesImpl.jar in our application classpath means that xerces is used ahead of the JDK, and therefore our XXE mitigations are useless.

XXE mitigation reference: https://www.owasp.org/index.php/XML_External_Entity_(XXE)_Prevention_Cheat_Sheet#TransformerFactory

Besides all of that: Xerces hasn't been maintained since 2010!

As has been mentioned by others: AntiSamy should be using XLST to serialize instead of the deprecated HTMLSerializer. As far as I can tell, this is the only direct xerces dependency.

Thanks.

**Comment by mjclemente** [comment]
Thanks so much for reviving and working on this project! I just wanted to add my support to this enhancement.

**Comment by wcruppel** [comment]
I am withdrawing this issue for the following reasons:
1) NekoHTML is also dependent on Xerces.
2) Xerces doesn't provide Transformer classes, that comes from Xalan (not a dependency of AntiSamy)
