### ISSUE TITLE
AntiSamy not detecting XSS for anchor tag

### ISSUE THREAD

**Issue by trcoelho** [nahsra/antisamy#214]
Hello!

Have used your library as a result to detect a mailicious string and prevent it to be injected on application, however I have figured out a scenario that can be possible as follows:

If I pass the following string:

`<a href='https://malicioussite.com/'>Click here<a/a>`

The method `getNumberOfErrors` from `CleanResults` class does not detect it as a malicous string.

Have tried all policies files available:

- antisamy.xml
- antisamy-anythinggoes.xml
- antisamy-ebay.xml
- antisamy-myspace.xml
- antisamy-slashdot.xml
- antisamy-tinymce.xml

and also all scan types:

- AntiSamy.SAX
- AntiSamy.DOM

and still `getNumberOfErrors` method does not detect it.

Curiously this string is successfully validated `<a href="http://malicious.com" target="blank_" />`.

Please find below my test scenario regargind this possible problem for testing porposes:
```
        String aHref01 = "<a href='https://malicioussite.com/'/>Click here";
	String aHref02 ="<a href=\\\"http://malicious.com.br\\\" target=\\\"blank_\\\" />\"\r\n"; // This is successfully validated

	List<URL> urls = new ArrayList<>();
	urls.add(this.getClass().getClassLoader().getResource("antisamy.xml"));
	urls.add(this.getClass().getClassLoader().getResource("antisamy-anythinggoes.xml"));
	urls.add(this.getClass().getClassLoader().getResource("antisamy-ebay.xml"));
	urls.add(this.getClass().getClassLoader().getResource("antisamy-myspace.xml"));
	urls.add(this.getClass().getClassLoader().getResource("antisamy-slashdot.xml"));
	urls.add(this.getClass().getClassLoader().getResource("antisamy-tinymce.xml"));

	for (URL url : urls) {
	    Policy policy = Policy.getInstance(url);
	    AntiSamy antiSamy = new AntiSamy(policy);

	    CleanResults crSAX = antiSamy.scan(aHref01, AntiSamy.SAX);
	    int numOfErrorsSAX = crSAX.getNumberOfErrors();
	    CleanResults crDOM = antiSamy.scan(aHref01, AntiSamy.DOM);
	    int numberOfErrorsDOM = crDOM.getNumberOfErrors();

	   assertTrue(numOfErrorsSAX > 0 && numberOfErrorsDOM > 0); // It fails
	   
	   
	}
```

I am using the AntiSammy version as follows:

```
<dependency>
       <groupId>org.owasp.antisamy</groupId>
	<artifactId>antisamy</artifactId>
	<version>1.7.0</version>
</dependency>
```
Do we have a known issue here or this is something new?

Thanks in advance.

**Comment by trcoelho** [comment]
Looks like the anchor tag needs an additional attribute to be validates, for instance:

`String anchorTagEx1 = "<a href='https://malicioussite.com/' target='blank_'>Click here</a>"; // This works and it is validated by AntiSammy`

`String anchorTagEx2 = "<a href='https://malicioussite.com/'>Click here</a>"; // This does not works and it is bypassed by AntiSammy`

And String "anchorTagEx2" is rendered by browsers.

Thanks in advance.

**Comment by davewichers** [comment]
@spassarop - Can you review/comment on the 2 posts to this Issue?

**Comment by spassarop** [comment]
@trcoelho sorry but it's not clear what you think the problem is. You first need to identify what is your expected output and the current one, then we can discuss whether it's OK or not.

I ran the following code in 1.7.0 with the default policy:
```java
    String aHref01 = "<a href='https://malicioussite.com/'/>Click here";
    String aHref02 ="<a href=\"http://malicious.com.br\" target=\"blank_\" />\"\r\n"; 

    CleanResults crDOM = as.scan(aHref01, policy, AntiSamy.DOM);
    System.out.println("Output 1: " + crDOM.getCleanHTML());
    System.out.println("Output 1 errors: " + crDOM.getNumberOfErrors());
    crDOM = as.scan(aHref02, policy, AntiSamy.DOM);
    System.out.println("Output 2: " + crDOM.getCleanHTML());
    System.out.println("Output 2 errors: " + crDOM.getNumberOfErrors());
```

And my outputs are:
```
Output 1: <a href="https://malicioussite.com/" rel="nofollow">Click here</a>
Output 1 errors: 0
Output 2: <a href="http://malicious.com.br" rel="nofollow">&quot; </a>

Output 2 errors: 1
```

The error in input 2 is `The a tag contained an attribute that we could not process. The target attribute has been filtered out, but the tag is still in place. The value of the attribute was "blank&#95;".` which is OK because `target` is not part of the policy. 

Also, you don't specify why you think the input is malicious. I don't see why an anchor tag is a problem as long it complies with the policy. Maybe you are trying to point it to reverse tabnabbing attacks, in that case I suggest you read issue #89.

**Comment by trcoelho** [comment]
Hi @spassarop .
The problem with an anchor tag is that a bad intentioned user might post / put a macilious input which can encourage other users to click, for instance:

Myself as a bad intencioned user, want to post an anchor tag `<a href='https://malicioussite.com/'/>Click here</a>` on a POST/PUT attribute parameter as a result to encourage other users to click and get sensitive information.

The `<a href='https://malicioussite.com/'/>Click here</a>` is successfully rendered on browsers as well as Chrome or Edge and antisamy does not detect it as a XSS input.

If the input has another attribute like `<a href='https://malicioussite.com/' target='blank_'/>Click here</a>` then it does detect as a XSS input:

Example 1 - Trying to sanitize and detect erros on anchor tag:
```
       // It hasn't any other attribute
       String aHref01 = "<a href='https://malicioussite.com/'/>Click here</a>";

	URL url = this.getClass().getClassLoader().getResource("antisamy.xml");

	Policy policy = Policy.getInstance(url);
	AntiSamy antiSamy = new AntiSamy(policy);

	CleanResults crSAX = antiSamy.scan(aHref01, AntiSamy.SAX);
	int numOfErrorsSAX = crSAX.getNumberOfErrors();
	String cleanHTMLSAX = crSAX.getCleanHTML();
	
	System.out.println("Number of errors SAX: " + numOfErrorsSAX);
	System.out.println("Clean HTML SAX: " + cleanHTMLSAX);
	
	
	CleanResults crDOM = antiSamy.scan(aHref01, AntiSamy.DOM);
	int numOfErrorsDOM = crDOM.getNumberOfErrors();
	String cleanHTMLDOM = crDOM.getCleanHTML();
	
	System.out.println("Number of errors DOM: " + numOfErrorsDOM);
	System.out.println("Clean HTML DOM: " + cleanHTMLDOM);
```
Output example 1:

```
Number of errors SAX: 0
Clean HTML SAX: <a href="https://malicioussite.com/" rel="nofollow">Click here</a>
Number of errors DOM: 0
Clean HTML DOM: <a href="https://malicioussite.com/" rel="nofollow">Click here</a>
```

---------------------------------------------------------------------------------------------------------------------

Example 2 - If the anchor tag has an attribute, AntiSammy library does detect it as a malicious input (which I believe should detect on example 1):

```
       // It has a "target" attribute
       String aHref01 = "<a href='https://malicioussite.com/' target='_blank'/>Click here</a>"; 

	URL url = this.getClass().getClassLoader().getResource("antisamy.xml");

	Policy policy = Policy.getInstance(url);
	AntiSamy antiSamy = new AntiSamy(policy);

	CleanResults crSAX = antiSamy.scan(aHref01, AntiSamy.SAX);
	int numOfErrorsSAX = crSAX.getNumberOfErrors();
	String cleanHTMLSAX = crSAX.getCleanHTML();
	
	System.out.println("Number of errors SAX: " + numOfErrorsSAX);
	System.out.println("Clean HTML SAX: " + cleanHTMLSAX);
	
	
	CleanResults crDOM = antiSamy.scan(aHref01, AntiSamy.DOM);
	int numOfErrorsDOM = crDOM.getNumberOfErrors();
	String cleanHTMLDOM = crDOM.getCleanHTML();
	
	System.out.println("Number of errors DOM: " + numOfErrorsDOM);
	System.out.println("Clean HTML DOM: " + cleanHTMLDOM);
```
Output example 2:
```
Number of errors SAX: 1
Clean HTML SAX: <a href="https://malicioussite.com/"
  rel="nofollow noopener noreferrer">Click here</a>
Number of errors DOM: 1
Clean HTML DOM: <a href="https://malicioussite.com/" rel="nofollow">Click here</a>
```

As you can see AntiSammy does clean HTML and detect that String has errors on example 2. Why it doesn't on example 1?


Let me know if you have any question.

**Comment by spassarop** [comment]
It’s simple. An anchor itself is not malicious. If YOU as a user do not
want to allow those because an attacker can introduce a bad href, you
change the policy to remove anchor tags. It’s just not possible to know if
the URL is malicious or not. There are some regular expressions in place to
validate bad URLs but not where they point to.

It’s not a vulnerability to have anchor tags and you can be as permissive
as you want. It’s customizable, you decide which tags, attributes and
values can be used. That’s not AntiSamy’s responsibility. We provide the
tool and process the input regarding the chosen policy.

The case 2 “validates” with a result because you use a disallowed attribute
“target” not because there is XSS. Your input does not comply with the
policies you used, only that.

I suggest you read the README and the wiki to understand how AntiSamy
works, there is no issue here. Thanks anyway for your time and reporting a
potential issue.

Dave, if you agree you can close this issue.

**Comment by trcoelho** [comment]
I am using `antisamy.xml` as policy file included on jar. So if I want to avoid anchor tags I would need to create my policy file and add this policy on it.

Is that correct?

**Comment by spassarop** [comment]
Yes, you can use any example policy as template. As most of them have the
anchor tag with the “validate” action, you can put “remove” instead of
deleting it from the policy.

Please test your policy well and read the wiki to understand how your
changes work :)

**Comment by trcoelho** [comment]
Got it! 
So why do we have different behaviors for

 `<a href='https://malicioussite.com/'/>Click here</a>` 
 and
  `<a href='https://malicioussite.com/' target='_blank'/>Click here</a>`
  
  ?
  
  I meant, why AntiSammy does detect errors on `<a href='https://malicioussite.com/' target='_blank'/>Click here</a>`  and it does not on `<a href='https://malicioussite.com/'/>Click here</a>`  ?

**Comment by trcoelho** [comment]
Well. 

Ok then. 

Still think that it should have same behaviour regardless target attribute.


Appreciate your support @spassarop !
