### ISSUE TITLE
Incorrect 'Contributing' link on OWASP wiki page

### ISSUE THREAD

**Issue by kwwall** [nahsra/antisamy#224]
On the [OWASP project wiki page for AntiSamy](https://owasp.org/www-project-antisamy/), on the right sidebar, under the 'Contacts' section, the link for 'Contributing' is a malformed mailto: link (the format for 'mailto:' just uses 'mailto:john.doe@example.com' and not 'mailto://john.doe@example.com'). Besides, it probably would be better to refer to the 'Contributing to AntiSamy' section of your README file, i.e., https://github.com/nahsra/antisamy/blob/main/README.md#contributing-to-antisamy, unless you are going to add some sort of default email subject to the mailto: link, like
```html
    mailto:theAwesomeAntiSamyDevs@example.com?subject=I%20would%20like%20to%20contribute%20to%20AntiSamy
```

Note also that the two 'mailto:' links under the Leaders section is similarly malformed in that they use 'mailto://'.

P.S.- This probably would be more appropriate on https://github.com/OWASP/www-project-antisamy/issues, but I wasn't sure if anyone was watching that space.

**Comment by davewichers** [comment]
Fixed on the OWASP site wiki today.  Thanks for reporting.
