### ISSUE TITLE
2 enhancement

### ISSUE THREAD

**Issue by k4n5ha0** [nahsra/antisamy#243]
1）when use default xml，antisamy print a warn：
![image](https://user-images.githubusercontent.com/22064977/194497154-1133ecb9-2d89-4efd-81ff-9a8e82ada0a1.png)

```
org.owasp.validator.html.Policy - The directive "noopenerAndNoreferrerAnchors" is enabled by default, but disabled in this policy. It is recommended to leave it enabled to prevent reverse tabnabbing attacks.
```
i think all default need add 
```
<directive name="noopenerAndNoreferrerAnchors" value="true" />
```

2)readme  need add antisamy-tinymce.xml info  in  
```
2. Choosing a base policy file
```

**Comment by davewichers** [comment]
@spassarop - can you look at suggestion 2? If you understand/agree, can you make an update? If its not clear what is being asked for, please work with the submitter to clarify. Thx

**Comment by davewichers** [comment]
Can we close this issue since you closed the related pull request?
