### ISSUE TITLE
1 enhancement with api

### ISSUE THREAD

**Issue by k4n5ha0** [nahsra/antisamy#245]
![image](https://user-images.githubusercontent.com/22064977/194706922-99a22d0e-020d-4c8a-aac1-6a7ac3daf899.png)
i think anti samy need a default Policy
so antisamy api keep pace with Sanitizer API
Sanitizer API： https://wicg.github.io/sanitizer-api/#intro

like code:
```
            String input = "?<scRipt> alErt(1)" +
                    " </Script>";
            AntiSamy as = new AntiSamy();
            CleanResults santized = as.scan(input);
            System.out.println(santized.getCleanHTML());
            return;
```
antisamy will use antisamy-slashdot.xml

**Comment by davewichers** [comment]
Since you closed the pull request, can we close this issue? If not, can you clearly explain what you mean by "i think AntiSamy needs a default Policy that keeps pace with Sanitizer API： https://wicg.github.io/sanitizer-api/#intro"

**Comment by k4n5ha0** [comment]
> Since you closed the pull request, can we close this issue? If not, can you clearly explain what you mean by "i think AntiSamy needs a default Policy that keeps pace with Sanitizer API： https://wicg.github.io/sanitizer-api/#intro"

sorry for that ,this pr https://github.com/nahsra/antisamy/pull/247
