### ISSUE TITLE
Antisamy changing the URL begnin pattern.

### ISSUE THREAD

**Issue by 007divyachawla** [nahsra/antisamy#28]
Been using Antisamy for one of my projects, after I inputting the URL something like this

https://www.google.com/terms-conditions/vacancy.html and click on save button the same URL mention above will change something to this https://www.google.com/ter-ms-conditions/vacancy.html.

terms- is been change to ter-ms-. Please give the solution.

**Comment by nahsra** [comment]
https://www.softwaretestinghelp.com/how-to-write-good-bug-report/
