### ISSUE TITLE
Enabled noopenerAndNoreferrerAnchors policy drops nofollow

### ISSUE THREAD

**Issue by nikowitt** [nahsra/antisamy#287]
Hi there,

using the noopenerAndNoreferrerAnchors policy effectively drops a "nofollow":
`
<a href="https://www.sobis.com" target="_blank" ref="nofollow">SOBIS</a>
`
is filtered to 
`
<a href="https://www.sobis.com" target="_blank" ref="noopener noreferrer">SOBIS</a>
`
whereas I would actually expect it to be
`
<a href="https://www.sobis.com" target="_blank" ref="nofollow noopener noreferrer">SOBIS</a>
`

Is there a specific reason or is this a case missed?

Thanks for clarification!
Regards,
Niko

**Comment by davewichers** [comment]
@spassarop - Another question for you.

**Comment by spassarop** [comment]
Sorry @nikowitt but I couldn't reproduce your results. If your custom policy accepts `target="_blank"` in `<a>` and has the directive `<directive name="noopenerAndNoreferrerAnchors" value="true" />` then I don't get why that is happening.

You will need to provide details on how that part of your policy is defined, for the anchor tag and the corresponding directives. Also it would be useful to have how you are calling the AntiSamy API to understand which parser (SAX or DOM) is taking effect.

**Comment by nikowitt** [comment]
Hi @spassarop , sure, I will have a look at this and provide working examples.

**Comment by nikowitt** [comment]
This is the part of the policy (modified version of the myspace policy):
````
 <directive name="noopenerAndNoreferrerAnchors" value="true"/>
(...)
<tag name="a" action="validate">
            <!--  onInvalid="filterTag" has been removed as per suggestion at OWASP SJ 2007 - just "name" is valid -->
            <attribute name="href"/>
            <attribute name="onFocus"/>
            <attribute name="target" onInvalid="removeAttribute">
                <literal-list>
                    <literal value="_blank"/>
                    <literal value="_parent"/>
                    <literal value="_top"/>
                </literal-list>
            </attribute>
            <attribute name="onBlur"/>
            <attribute name="nohref">
                <regexp-list>
                    <regexp name="anything"/>
                </regexp-list>
            </attribute>
            <attribute name="rel">
                <regexp-list>
                    <regexp value=" *((nofollow|noopener|noreferrer) *){1,3}"/>
                </regexp-list>
            </attribute>
            <attribute name="name"/>
        </tag>
````
The issue happens with both DOM and SAX parsers whereas the DOM parser also reorganizes the order of some attributes.

Now I understood the case. In my use case the nofollowAnchors policy is disabled. This then always seems  to drop the "nofollow" in ref, whereas I expected it to remain as it was provided in ref. Enabling the "nofollowAnchors" directive always adds "nofollow", but then it is always added.

I guess this could be in general counter intuitive, but it's OK in my case.

**Comment by spassarop** [comment]
That is still odd. I used the myspace example policy with your `<a>` configuration and just the `noopenerAndNoreferrerAnchors` directive as `true` and I don't have that issue. In fact, the code that adds `nofollow` , `noopener` or `noreferrer` does not remove anything. It checks if the values are present to prevent repetition and deletion of the current text. The only way it could be deleted is that `rel` does not comply with the policy because it's not present, however, it's not the case so I don't have more information to answer anything else.

**Comment by nikowitt** [comment]
Thanks for the feedback. When I can spare the time, I will also do some additional checks. Until then, I will close it for the being.

**Comment by BloodDrag0n** [comment]
I have came across the same issue. We are using custom rules and version 1.6.4
