### ISSUE TITLE
Covering all cases of "rel" attribute in "anchor" tag is quite verbose

### ISSUE THREAD

**Issue by nikowitt** [nahsra/antisamy#288]
Hi there,
while introducing the noopenerAndNoreferrerAnchors policy, we found out that we have to maintain a literal list of "rel" in the policy file (some parts are omitted for brevity):

        <tag name="a" action="validate">
            <attribute name="rel">
                <literal-list>
                    <literal value="nofollow"/>
                    <literal value="noopener"/>
                    <literal value="noreferrer"/>

                    <literal value="nofollow noopener"/>
                    <literal value="nofollow noreferrer"/>

                    <literal value="nofollow noopener noreferrer"/>
                    <literal value="nofollow noreferrer noopener"/>

                    <literal value="noopener nofollow "/>
                    <literal value="noopener noreferrer"/>

                    <literal value="noopener nofollow noreferrer"/>
                    <literal value="noopener noreferrer nofollow"/>

                    <literal value="noreferrer nofollow"/>
                    <literal value="noreferrer noopener"/>

                    <literal value="noreferrer nofollow noopener"/>
                    <literal value="noreferrer noopener nofollow"/>
                </literal-list>
            </attribute>
            <attribute name="name"/>

        </tag>

Otherwise, any unexpected order of keywords in the value will raise a validation error. As this is quite cumbersome and hard to maintain, I am wondering if I miss something that would allow me to streamline the defined combination?

Thanks in advance!
Regards,
Niko

**Comment by davewichers** [comment]
@spassarop - Another question.

**Comment by spassarop** [comment]
Hi @nikowitt, you are right, defining literal combinations is cumbersome. That's why you will find a regular expression in the example policy that offers valid content. It allows many spaces but do no harm in the end:
```xml
<tag name="a" action="validate">
    ...
    <attribute name="rel">
        <regexp-list>
            <regexp value="(\s*(nofollow|noopener|noreferrer)(\s(nofollow|noopener|noreferrer))*\s*)?" />
        </regexp-list>
    </attribute>
    ...
</tag>
```
There is no easier way by design to contemplate such variations in the value. If you are satisfied with this answer then close the issue.

**Comment by nikowitt** [comment]
Hi @spassarop, thanks for the hint. I guess this might work out, even though it is not beautiful :)

Closing as it is fine for me.
