### ISSUE TITLE
How to find if vulnerable script is present in the input

### ISSUE THREAD

**Issue by mathewm3** [nahsra/antisamy#356]
Hi Team,

We had the method - _getNumberOfErrors()_ to check whether the input contained any vulnerable script. According to the release notes, this method doesn't confirm whether the input is safe.

We tried the following alternative to check whether input contained any vulnerable script but in vain:

- We compared the input with the result from the method - _getCleanHTML()_ . But there are too many special characters like '\n, \r, &nbsp etc being added. It almost becomes impossible to compare in a foolproof way. We also modified "formatOutput" to false, but that also did not help.

**Sample input**
```
<p><strong>NAME:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; John Doe&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;GENDER:</strong>&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Male</p>
<p></p>
<p><strong>COUNTRY:&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; United States&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;</strong><strong>JOB :</strong>&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; Yet to figure out</p>
<p>&nbsp;</p>
<p><span style="font-weight: normal;"><span style="color: black;"><span style="font-size: 10pt;">Required to complete other activities before proceeding further.</span></span></span></p>
```

**Cleaned HTML from AntiSamy**
`<p><strong>NAME:                    John Doe                                                 GENDER:</strong>                       Male</p> <p></p> <p><strong>COUNTRY:               United States                                                 </strong><strong>JOB :</strong>               Yet to figure out</p> <p> </p> <p><span style="font-weight: normal;"><span style="color: black;"><span style="font-size: 10.0pt;">Required to complete other activities before proceeding further.</span></span></span></p>`

**Do we have any utility to check and confirm whether the input contained any vulnerable script?**

**Comment by mathewm3** [comment]
Just to highlight the difference between input and output.

1. &nbsp is replaced with  "\u00A0" (unicode 160)
2. font-size: 10pt; is replaced with font-size: 10.0pt;

There could be many more of those. 

**If we have any utility or a method which confirms whether the input contains a vulnerable script, it will be super useful.**

**Comment by kwwall** [comment]
@spassarop - Please correct me if I'm wrong, but @mathewm3, I believe that what `getCleanHTML` returns can be considered _safe_. The `getNumberOfErrors` method was never intended for that purpose.

**Comment by spassarop** [comment]
Yes, only getCleanHTML. The auxiliary methods to get number of errors or
errors list are to find out how the applied policy acted on the validation
process.

A policy may say `<style>` is not allowed and a new “error” would be added
to the list saying the tag gets removed by policy. That may happen with
other scenarios that aren’t necessarily vulnerability-related.

Sadly there’s no utility to check if some output is “safe” and as it was
pointed out, output changes in many details sometimes, trying to be the
most equivalent to the original input. In the end, safety is based on
trust, on the tool and the defined policy.

**Comment by mathewm3** [comment]
Thanks a lot, @spassarop and @kwwall for the quick and prompt response.

**Comment by kwwall** [comment]
@mathewm3 - while I realize that you've closed this issue and thus this may be irrelevant, I personally am rather lost because you present us with an implementation, and yet have failed to address what specific problem are you trying to solve. If you are just trying to run a JUnit test with specific input you are passing to AntiSamy, that's one thing, but if you are trying to write a regex that provides some protection to your application, I would say that even that is risky. Trying to use a regex to match arbitrary HTML is brittle at best and generally will fail in catastrophic ways except for very well defined contexts. So, if you are just trying to fix a broken JUnit test that previously was using `getNumberOfErrors` and now is no longer working, this approach likely will work. However, if you are dropping this into your code to provide a robust defense against XSS, I feel compelled to back you up and ask "What exactly mark-up are you expecting to accept in this context?" That is, what problem are you trying to solve?

**Comment by mathewm3** [comment]
Sorry for the confusion. The above code is to fix a broken Junit test/scenario after getting cleaned HTML. We are not using the above code to check whether there are any XSS issues.

**Comment by kwwall** [comment]
Glad to hear that and happy you got your JUnit tests worked out.
