### ISSUE TITLE
Injecting js in "a" tag

### ISSUE THREAD

**Issue by sk2atlas** [nahsra/antisamy#37]
Still able to inject `<a onmouseover=alert(1)>click</a>, <p onmouseover=alert(1)>click</p>` element. Even though I have updated the antisamy policy to remove "a" tag completely

**Comment by davewichers** [comment]
Can you provide the exact policy change you've implemented so we can try to reproduce this behavior?

**Comment by sk2atlas** [comment]
```<tag name="a" action="remove"/>```

**Comment by davewichers** [comment]
I just tested this policy and it worked fine for me.  Are you sure you are putting this new policy change into the antisamy.xml file in the proper place, and the modified antisamy.xml file is actually being used by your test?

In my test I did this:
  Policy policy = Policy.getInstance("PathTo/My/Custom/policy/antisamy_37.xml");
  AntiSamy as = new AntiSamy():
  System.out.println(as.scan("Test XML String Goes Here", policy, AntiSamy.SAX).getCleanHTML());
  System.out.println(as.scan("Test XML String Goes Here", policy, AntiSamy.DOM).getCleanHTML());

And in both cases all the <a> tags  got stripped out of the Test XML String.

And in antisamy_37.xml, I added: <tag name="a" action="remove"/> in the <tag-rules> block of the antisamy.xml file.

Are you testing like this? If not, can you try and verify it actually does (or does not) work for you?

**Comment by davewichers** [comment]
Given that this worked for me, and @sk2atlas hasn't responded with more details to confirm this issue, I'm closing this. Feel free to reopen if you can provide a working example of this failure.
