### ISSUE TITLE
Performance got degraded after upgrade from 1.5.7 version to 1.5.8 for the SAXScanner.

### ISSUE THREAD

**Issue by dharmendra027** [nahsra/antisamy#39]
After upgrading antisamy jar version from 1.5.7 to 1.5.8 performance got down by 40-50%.
After comparing the 1.5.8 version of code with the 1.5.7. I found that in case of SAXScanner, in the class **AntiSamySAXScanner** after doing all the scanning process the cached item is not being added to the **cachedItems** Queue, because of which for every scan call object of **CachedItem**  class is being created.
And this create operation for every scan is lowering down the performance.

**Comment by dharmendra027** [comment]
Any feedback on my PR ? Do I need to describe further the purpose of this fix ?

**Comment by davewichers** [comment]
I think we need @davidbarbrowatwork to review your requested change because I believe it was his changes to 1.5.8 that affected the code you are trying to fix. Can you try to find/nudge him to get him to review/approve your requested change?

**Comment by dharmendra027** [comment]
Hi @davidbarbrowatwork, I found the performance is down by almost 50% in the 1.5.8 antisamy version comapre to 1.5.7.
I have debugged the issue and raised a pull request for it on @davewichers repository.
Can you please review it once its a urgent for me.

**Comment by dharmendra027** [comment]
Hi @davewichers , can you please try to connect to @davidbarbrowatwork to review this PR, as I couldn't get any response from.

**Comment by davewichers** [comment]
I tried as well, but I can try again. You can find him and try on Twitter.

Dave

**Comment by dharmendra027** [comment]
Hi @davewichers, if you have twitter id of @davidbarbrowatwork can you please share.

Thanks

**Comment by davewichers** [comment]
I think it is @ dbarbrow.

**Comment by dharmendra027** [comment]
Hi @davewichers,
Is the master branch of this repo is 1.5.8? I found the pom.xml of master master branch have project version 1.5.8 and could not find any specific branch for 1.5.8.

**Comment by davewichers** [comment]
This is the 1.5.8 release: https://github.com/nahsra/antisamy/releases and I believe there is a checkin tag for that release.
I've created a 1.5.9 branch, so I suggest you make any suggested changes to that branch. Hopefully you can add test cases that show the slowdown you are talking about, but correct behavior otherwise. And then when we add your requested change we can see a significant performance improvement but the same correct functionality verified by the test case.

**Comment by dharmendra027** [comment]
Hi @davewichers, Change that i have made was present in the branches below 1.5.8.

For example 

- In version 1.5.4: line number 131 of https://github.com/nahsra/antisamy/blob/1.5.4/src/main/java/org/owasp/validator/html/scan/AntiSamySAXScanner.java
- -Version 1.5.5: line number 131 of https://github.com/nahsra/antisamy/blob/1.5.5/src/main/java/org/owasp/validator/html/scan/AntiSamySAXScanner.java
- -Version 1.5.6: https://github.com/nahsra/antisamy/blob/1.5.6/src/main/java/org/owasp/validator/html/scan/AntiSamySAXScanner.java
- Version 1.5.7: line number 131 of https://github.com/nahsra/antisamy/blob/1.5.7/src/main/java/org/owasp/validator/html/scan/AntiSamySAXScanner.java

And I got an instruction to use 1.5.8 version of the Antisamy.So I request to please consider it for version 1.5.8.
Thanks

**Comment by davewichers** [comment]
The requested line has been added, and this fix was just released in version v1.5.9 of AntiSamy, along with a few dependency upgrades.
