### ISSUE TITLE
AntiSamy Bypass - looking for security contact

### ISSUE THREAD

**Issue by prodigysml** [nahsra/antisamy#40]
I'm reasonably sure that I found a bypass leading to XSS. Can I please get a contact to further discuss this issue?

**Comment by davewichers** [comment]
Sure. Just send me a note directly to: dave dot wichers at owasp dot org, and I'll research/discuss with Arshan as necessary. Thanks for keeping your concerns private.

**Comment by kwwall** [comment]
@davewichers -- You might want to consider addressing how to report
vulnerabilities directly in your README.md file like we did in ESAPI. (We
also linked to a SECURITY.md file so we could keep it short and sweet in
the README.md.)

-kevin
--
Blog: http://off-the-wall-security.blogspot.com/  |  Twitter:  @KevinWWall
NSA: All your crypto bit are belong to us.

**Comment by davewichers** [comment]
@prodigysml - per our email exchange I believe what you have reported is a false positive. As such, I'm closing this issue. However, if you figure out anything new, please let me know offline. @kwwall - good idea. I've updated README and added a SECURITY.md file which I'll check in soon.
