### ISSUE TITLE
Antisamy adds nested table tags

### ISSUE THREAD

**Issue by devapriya-k** [nahsra/antisamy#42]
Input 
![image](https://user-images.githubusercontent.com/32926580/82233118-1f025700-994d-11ea-8004-01bb2df33f1c.png)

**Output after antisamy scan**
![image](https://user-images.githubusercontent.com/32926580/82233196-40fbd980-994d-11ea-8c18-f56f0268e250.png)

 
After scanning, additional nested table close tags `</tbody></table></td></tr>` are added a line before img tag  and so output becomes distorted. using antisamy.xml and not sure why nested table related tags are getting added after antisamy scan.

**Comment by devapriya-k** [comment]
Team, can you please let me know how to avoid this issue ?

**Comment by nahsra** [comment]
Can you provide a failing unit test in a PR, or at least provide the text for the above, as translating to text from the image would be quite time consuming?

**Comment by devapriya-k** [comment]
Hey @nahsra  Thanks for your input here. Tomcat upgrade from 7 to 9 helped to resolve this issue.

**Comment by davewichers** [comment]
@devapriya-k - given it is now working for you, can we close this issue?

**Comment by devapriya-k** [comment]
yes , we can close it and thanks for the response team.
