### ISSUE TITLE
Prevent formatting and translation of css

### ISSUE THREAD

**Issue by tom-mayer** [nahsra/antisamy#438]
Hi,

I'm have an antisamy configuration based on the `myspace.xml`, for this problem we can assume it is exactly that configuration.  we also disabled `formatOutput`. When I run our html through the scan it transforms some css values which in our case is not disireable, namely:

- A width value of e.g. `width: 100px`  will be transformed to `width: 100.0px`
- A color value of e.g. `background-color:#bfbfbf` will be transformed to `background-color: rgb(191,191,191)` 

Is there any way to prevent this?  Antisamy also seems to add/remove spaces and add semicolons in `style` properties. 

Cheers and thanks!

**Comment by davewichers** [comment]
@spassarop - A question for you! :-)

**Comment by spassarop** [comment]
Hi @tom-mayer. Sorry but it is not possible to avoid that. If your inputs accept CSS validation, AntiSamy needs to parse and analyze that text using an abstract representation of it. On the process of reconstructing the text, the dependency AntiSamy uses to generate back the CSS has that kind of behavior. It has no context on how the CSS was before in literal text. Therefore, you need to adapt to that.

Hope you find a way that AntiSamy still suits your needs.

**Comment by tom-mayer** [comment]
Hi thanks for the answer! I thought so, I just wanted to make sure I'm not missing something obvious here.
