### ISSUE TITLE
Usage of vulnerable commons-httpclient library

### ISSUE THREAD

**Issue by ggraat** [nahsra/antisamy#6]
Hi,

This library has a dependency on the commons-httpclient library which is both end of life and vulnerable. Is it possible to upgrade to its replacement, http://hc.apache.org/httpcomponents-client-ga/index.html?

Thanks,
Geert

**Comment by nahsra** [comment]
I think its downstream of one of our dependencies. I'll look into it. Sorry for the late reply!

**Comment by nahsra** [comment]
The only function that needed an HTTP client was the embedStyleSheets toggle, which I think no one uses, and doesn't work anyway from my limited testing. Will fix or remove that in a later version.

**Comment by nahsra** [comment]
Marked as dupe of #7
