### ISSUE TITLE
Update batik-css to 1.14

### ISSUE THREAD

**Issue by NikolayMetchev** [nahsra/antisamy#70]
This would address a vulnerability in a downstream dependency
https://app.snyk.io/vuln/SNYK-JAVA-ORGAPACHEXMLGRAPHICS-1079038

**Comment by davewichers** [comment]
This has already been addressed in the 1.6.0 branch. When that branch is merged into trunk with the release of 1.6.0, this will be addressed.

**Comment by davewichers** [comment]
This was addressed in commit 3f446c5691e2111c15121a176d9b0994ded3ea42 and AntiSamy v1.6.0 was released today with this included.
